### ISSUE TITLE
Entire content of events in calendar is clickable

### ISSUE THREAD

**Issue by myth** [dotkom/glowing-fortnight#10]
The event description is currently rendered as a clickable for toggling expansion of the event, which makes it impossible to mark text in some browsers, or possibly also to click markdown-parsed urls.

**Comment by tmn** [comment]
The anchor is causing this. Turning it back into something else would do. However, this solution will remove the snappy snap to title thingy. 

Maybe considering adding a click event to the element without using an anchor, and make the transition a little smoother. The latter part could be somehow tricky :smile:

**Comment by OptimusCrime** [comment]
Is it possible to turn off the snap to calendar-title functionality upon click? While it is a good idea for direct links, I find it rather annoying when clicking the links to browse the description.

**Comment by myth** [comment]
The splash is made with focus on mobile. If you have one event expanded which has a lot of info, and then click another event further down, the last event you clicked might disappear out of the screen entirely. That was the main reason for adding snapping on click. We were aware that it did feel too aggressive on desktop, but didn't have the time to figure out a solution that still solves the mobile issue.
