### ISSUE TITLE
Previous days are shuffled into preDays at 02:00, not 00:00

### ISSUE THREAD

**Issue by plusk** [dotkom/glowing-fortnight#15]
This is due to timey wimey zone stuff. The if-statement that guards the preDays.push evaluates as false for two hours between midnight and 02:00 when we want it to evaluate to true. The cause seems to be that the two Dates that are compared aren't in the same timezone (?).

**Comment by plusk** [comment]
This shouldn't be too hard to fix, will probably handle it along with #16. Might also pull inn Moment.js for the sake of trying it out and simplifying things a tidbit.

**Comment by nornes** [comment]
When ititiating the Date-object with a date it sets it to UTF, which is 2 hours behind us. When setting just `new Date()` it sets it to local time.

**Comment by plusk** [comment]
I think you mean UTC. :stuck_out_tongue: 
Other than that though, you're absolutely right. Simply shifting the date two hours would be simple, but that doesn't account for daylight savings (not that the splash is ever used during the winter). 
As mentioned earlier, we're probably better off using Moment.js and saving ourselves a fair amount of headache. Doing #16 simultaneously could help clean up the logic in the calendar component in general. Feel free to take a shot at it, we have about a year until it needs to be fixed.

**Comment by nornes** [comment]
you can set a variable to account for the offset `timezoneOffset = (new Date).getTimezoneOffset()` and add that to the time. It returns minutes, so you might have to do some calculations, but it should account for daylight savings as well i think.
